$ErrorActionPreference = 'Stop'
$configPath = Join-Path $PSScriptRoot 'VotV\Binaries\Win64\Mods\VotVCoopPrototype\config.ini'

if (-not (Test-Path -LiteralPath $configPath)) {
    Write-Host 'Mod files not found. Extract the entire archive next to VotV.exe.' -ForegroundColor Red
    exit 1
}

Write-Host 'VotV Coop Prototype setup' -ForegroundColor Cyan
Write-Host '1 - Host on this computer'
Write-Host '2 - Connect this computer to a host'
$choice = Read-Host 'Select 1 or 2'

if ($choice -eq '1') {
    $role = 'host'
    $hostAddress = '127.0.0.1'
} elseif ($choice -eq '2') {
    $role = 'client'
    $hostAddress = Read-Host 'Host IPv4 address (example: 192.168.1.25)'
    if ($hostAddress -notmatch '^(?:\d{1,3}\.){3}\d{1,3}$') {
        Write-Host 'Address must be IPv4, for example 192.168.1.25.' -ForegroundColor Red
        exit 1
    }
} else {
    Write-Host 'Unknown option.' -ForegroundColor Red
    exit 1
}

$playerName = Read-Host 'Player name'
if ([string]::IsNullOrWhiteSpace($playerName)) { $playerName = $env:USERNAME }
$playerName = $playerName.Replace('|', '_').Replace('"', '')

$portText = Read-Host 'UDP port (Enter = 27071)'
if ([string]::IsNullOrWhiteSpace($portText)) { $portText = '27071' }
$port = 0
$portParsed = [int]::TryParse($portText, [ref]$port)
if ((-not $portParsed) -or ($port -lt 1) -or ($port -gt 65535)) {
    Write-Host 'Port must be between 1 and 65535.' -ForegroundColor Red
    exit 1
}

$config = @(
    '# Generated by CoopSetup.ps1'
    "role=$role"
    "host=$hostAddress"
    "port=$port"
    "name=$playerName"
) -join "`r`n"

$utf8WithoutBom = New-Object System.Text.UTF8Encoding -ArgumentList $false
[System.IO.File]::WriteAllText($configPath, $config, $utf8WithoutBom)
Write-Host "Ready: mode $role, address $hostAddress, port $port, name $playerName." -ForegroundColor Green
Write-Host 'Now launch VotV.exe normally.'
