$ErrorActionPreference = 'Stop'
$configPath = Join-Path $PSScriptRoot 'VotV\Binaries\Win64\Mods\VotVCoopPrototype\config.ini'

$sourceCandidates = @(
    $env:VOTV_COOP_MOD_PATH,
    $env:VOTV_MOD_PATH,
    (Join-Path $PSScriptRoot '..\votv-coop-prototype\mod'),
    (Join-Path $PSScriptRoot '..\mod'),
    (Join-Path $PSScriptRoot '..\..\mod'),
    (Join-Path $PSScriptRoot 'mod')
) | Where-Object { -not [string]::IsNullOrWhiteSpace($_) }

$sourceMod = $null
foreach ($candidate in $sourceCandidates) {
    if (Test-Path -LiteralPath (Join-Path $candidate 'scripts') -PathType Container) {
        $sourceMod = (Resolve-Path -LiteralPath $candidate).Path
        break
    }
}

if ($sourceMod) {
    $targetMod = Join-Path $PSScriptRoot 'VotV\Binaries\Win64\Mods\VotVCoopPrototype'
    $targetScripts = Join-Path $targetMod 'scripts'
    if (-not (Test-Path -LiteralPath $targetScripts -PathType Container)) {
        New-Item -ItemType Directory -Path $targetScripts -Force | Out-Null
    }
    Copy-Item -Path (Join-Path $sourceMod 'scripts\*.lua') -Destination $targetScripts -Force
    if (Test-Path -LiteralPath (Join-Path $sourceMod 'enabled.txt')) {
        Copy-Item -Path (Join-Path $sourceMod 'enabled.txt') -Destination $targetMod -Force
    }
}

if (-not (Test-Path -LiteralPath $configPath)) {
    Write-Host 'Mod files not found. Extract the entire archive next to VotV.exe.' -ForegroundColor Red
    exit 1
}

Write-Host 'VotV Coop Prototype setup' -ForegroundColor Cyan
Write-Host '1 - Host on this computer'
Write-Host '2 - Connect this computer to a host'
$choice = Read-Host 'Select 1 or 2'

if ($choice -eq '1') {
    $role = 'host'
    $hostAddress = '127.0.0.1'
} elseif ($choice -eq '2') {
    $role = 'client'
    $hostAddress = Read-Host 'Host IPv4 address (example: 192.168.1.25)'
    if ($hostAddress -notmatch '^(?:\d{1,3}\.){3}\d{1,3}$') {
        Write-Host 'Address must be IPv4, for example 192.168.1.25.' -ForegroundColor Red
        exit 1
    }
} else {
    Write-Host 'Unknown option.' -ForegroundColor Red
    exit 1
}

$playerName = Read-Host 'Player name'
if ([string]::IsNullOrWhiteSpace($playerName)) { $playerName = $env:USERNAME }
$playerName = $playerName.Replace('|', '_').Replace('"', '')

$portText = Read-Host 'UDP port (Enter = 27071)'
if ([string]::IsNullOrWhiteSpace($portText)) { $portText = '27071' }
$port = 0
$portParsed = [int]::TryParse($portText, [ref]$port)
if ((-not $portParsed) -or ($port -lt 1) -or ($port -gt 65535)) {
    Write-Host 'Port must be between 1 and 65535.' -ForegroundColor Red
    exit 1
}

$config = @(
    '# Generated by CoopSetup.ps1'
    "role=$role"
    "host=$hostAddress"
    "port=$port"
    "name=$playerName"
) -join "`r`n"

$utf8WithoutBom = New-Object System.Text.UTF8Encoding -ArgumentList $false
[System.IO.File]::WriteAllText($configPath, $config, $utf8WithoutBom)
Write-Host "Ready: mode $role, address $hostAddress, port $port, name $playerName." -ForegroundColor Green
Write-Host 'Now launch VotV.exe normally.'
